//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLManagement.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SQLManagement.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap back {
            get {
                object obj = ResourceManager.GetObject("back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DatabaseEdit {
            get {
                object obj = ResourceManager.GetObject("DatabaseEdit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DatabaseOpen {
            get {
                object obj = ResourceManager.GetObject("DatabaseOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DatabaseRemove {
            get {
                object obj = ResourceManager.GetObject("DatabaseRemove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DataContainer_MoveNextHS {
            get {
                object obj = ResourceManager.GetObject("DataContainer_MoveNextHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap delete1 {
            get {
                object obj = ResourceManager.GetObject("delete1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EditInformationHS1 {
            get {
                object obj = ResourceManager.GetObject("EditInformationHS1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap editstyle2 {
            get {
                object obj = ResourceManager.GetObject("editstyle2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gear {
            get {
                object obj = ResourceManager.GetObject("gear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Information {
            get {
                object obj = ResourceManager.GetObject("Information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap newstyle3 {
            get {
                object obj = ResourceManager.GetObject("newstyle3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Output {
            get {
                object obj = ResourceManager.GetObject("Output", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PrimaryKeyHS {
            get {
                object obj = ResourceManager.GetObject("PrimaryKeyHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PrimaryKeyHS1 {
            get {
                object obj = ResourceManager.GetObject("PrimaryKeyHS1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Refresh {
            get {
                object obj = ResourceManager.GetObject("Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap saveall {
            get {
                object obj = ResourceManager.GetObject("saveall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare @cmplevel int
        ///select @cmplevel = cmptlevel 
        ///from  master..sysdatabases 
        ///where name = DB_NAME()
        ///
        ///SELECT 
        ///	dbo.sysreferences.constid as id, dbo.sysobjects.id as tableId,
        ///	CASE WHEN @cmplevel &lt; 90  THEN USER_NAME(dbo.sysobjects.uid) ELSE SCHEMA_NAME(dbo.sysobjects.uid) END AS owner
        ///	, (CASE WHEN @cmplevel &lt; 90  THEN USER_NAME(dbo.sysobjects.uid) ELSE SCHEMA_NAME(dbo.sysobjects.uid) END) + &apos;.&apos; + (OBJECT_NAME(dbo.sysobjects.id)) AS tableName
        ///	, (CASE WHEN @cmplevel &lt; 90  THEN USER_NAME(dbo.sysob [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Script_GetAllForeignKeys {
            get {
                return ResourceManager.GetString("Script_GetAllForeignKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare @cmplevel int
        ///select @cmplevel = cmptlevel 
        ///from  master..sysdatabases 
        ///where name = DB_NAME()
        ///
        ///
        ///SELECT O.id as objectID, I.indid as indexID, CAST(O.id AS VARCHAR) + &apos;,&apos; + CAST(I.indid AS VARCHAR) as completeindexID
        ///	, CASE WHEN @cmplevel &lt; 90 
        ///		THEN USER_NAME(O.uid) 
        ///		ELSE SCHEMA_NAME(O.uid) 
        ///	END &apos;owner&apos;
        ///	, O.name as objectName
        ///	, ( CASE WHEN @cmplevel &lt; 90 THEN USER_NAME(O.uid) ELSE SCHEMA_NAME(O.uid) END ) + &apos;.&apos; + (I.name) as completename
        ///	, I.name as indexName,CASE O.xtype WHEN &apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Script_GetAllIndexes {
            get {
                return ResourceManager.GetString("Script_GetAllIndexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare @cmplevel int
        ///select @cmplevel = cmptlevel 
        ///from  master..sysdatabases 
        ///where name = DB_NAME()
        ///
        ///	
        ///SELECT 
        ///	object_id((CASE WHEN @cmplevel &lt; 90  THEN USER_NAME(dbo.sysobjects.uid) ELSE SCHEMA_NAME(dbo.sysobjects.uid) END) + &apos;.&apos; + (dbo.sysindexes.name)) as id 
        ///	, dbo.sysobjects.id as tableId
        ///	, CASE WHEN @cmplevel &lt; 90  THEN USER_NAME(dbo.sysobjects.uid) ELSE SCHEMA_NAME(dbo.sysobjects.uid) END AS tableOwner
        ///	, (CASE WHEN @cmplevel &lt; 90  THEN USER_NAME(dbo.sysobjects.uid) ELSE SCHEMA_NAME(db [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Script_GetAllPrimaryKeys {
            get {
                return ResourceManager.GetString("Script_GetAllPrimaryKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare @cmplevel int select @cmplevel = cmptlevel from  master..sysdatabases where name = DB_NAME()
        ///select 
        ///	so.*,
        ///	CASE WHEN @cmplevel &lt; 90  THEN USER_NAME(so.uid) ELSE SCHEMA_NAME(so.uid) END  &apos;owner&apos;,
        ///	(so.name) as &apos;qualifiedname&apos;
        ///from sysobjects so
        ///where ( so.xtype = &apos;U&apos;) 
        ///order by 
        ///  CASE WHEN @cmplevel &lt; 90  THEN USER_NAME(so.uid) ELSE SCHEMA_NAME(so.uid) END
        /// ,so.name.
        /// </summary>
        internal static string Script_GetAllUserDefinedTables {
            get {
                return ResourceManager.GetString("Script_GetAllUserDefinedTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare @cmplevel int
        ///select @cmplevel = cmptlevel 
        ///from  master..sysdatabases 
        ///where name = DB_NAME()
        ///
        ///SELECT 
        ///	C.constid as id
        ///	, O.id as tableId
        ///	, CASE WHEN @cmplevel &lt; 90 THEN USER_NAME(O.uid) ELSE SCHEMA_NAME(O.uid) END  as owner
        ///	, O.name as tablename
        ///	, OBJECT_NAME(C.constid) as name
        ///	, (CASE WHEN @cmplevel &lt; 90 THEN USER_NAME(O.uid) ELSE SCHEMA_NAME(O.uid) END )+ &apos;.&apos; + (OBJECT_NAME(C.constid)) as completeCheckName
        ///	,CASE (C.status&amp;0x004000) WHEN 0x004000 THEN &apos;Disabled&apos; ELSE &apos;Enabled&apos; E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Script_GetCheckConstraints {
            get {
                return ResourceManager.GetString("Script_GetCheckConstraints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare @cmplevel int
        ///select @cmplevel = cmptlevel 
        ///from  master..sysdatabases 
        ///where name = DB_NAME()
        ///
        ///SELECT 
        ///	C.constid as id
        ///	, O.id as tableId
        ///	, CASE WHEN @cmplevel &lt; 90 THEN USER_NAME(O.uid) ELSE SCHEMA_NAME(O.uid) END  as owner
        ///	, O.name as tablename
        ///	, OBJECT_NAME(C.constid) as name
        ///	, (CASE WHEN @cmplevel &lt; 90 THEN USER_NAME(O.uid) ELSE SCHEMA_NAME(O.uid) END )+ &apos;.&apos; + (OBJECT_NAME(C.constid)) as completeCheckName
        ///	,CASE (C.status&amp;0x004000) WHEN 0x004000 THEN &apos;Disabled&apos; ELSE &apos;Enabled&apos; E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Script_GetConstraintIdByName {
            get {
                return ResourceManager.GetString("Script_GetConstraintIdByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare @cmplevel int
        ///select @cmplevel = cmptlevel 
        ///from  master..sysdatabases 
        ///where name = DB_NAME()
        ///
        ///SELECT 	
        ///	CASE WHEN @cmplevel &lt; 90 
        ///		THEN USER_NAME(types1.uid) 
        ///		ELSE SCHEMA_NAME(types1.uid) 
        ///	END &apos;owner&apos;,
        ///	CASE WHEN (CASE WHEN @cmplevel &lt; 90  THEN USER_NAME(types1.uid) ELSE  SCHEMA_NAME(types1.uid) END ) = &apos;sys&apos; 
        ///		THEN LOWER(types1.name)  
        ///		ELSE LOWER( ((CASE WHEN @cmplevel &lt; 90  THEN USER_NAME(types1.uid) ELSE  SCHEMA_NAME(types1.uid) END )) + &apos;.&apos; + (types1.name)) 
        ///	END AS &apos;name&apos;, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Script_GetDataTypes {
            get {
                return ResourceManager.GetString("Script_GetDataTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare @cmplevel int
        ///select @cmplevel = cmptlevel 
        ///from  master..sysdatabases 
        ///where name = DB_NAME()
        ///
        ///SELECT 
        ///	id
        ///	, (CASE WHEN @cmplevel &lt; 90 THEN USER_NAME(uid) ELSE SCHEMA_NAME(uid) END ) + &apos;.&apos; + (name) as name
        ///	, CASE WHEN @cmplevel &lt; 90 THEN USER_NAME(uid) ELSE SCHEMA_NAME(uid) END  as UserId
        ///	, name as defaultName
        ///	, crdate 
        ///FROM sysobjects 
        ///	WHERE type=&apos;D&apos; AND id NOT IN (SELECT constid FROM sysconstraints)
        ///ORDER BY
        ///	CASE WHEN @cmplevel &lt; 90 THEN USER_NAME(uid) ELSE SCHEMA_NAME(uid) EN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Script_GetDefaults {
            get {
                return ResourceManager.GetString("Script_GetDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare @cmplevel int
        ///select @cmplevel = cmptlevel 
        ///from  master..sysdatabases 
        ///where name = DB_NAME()
        ///
        ///SELECT 
        ///	dbo.sysreferences.constid as id, dbo.sysobjects.id as tableId,
        ///	CASE WHEN @cmplevel &lt; 90  THEN USER_NAME(dbo.sysobjects.uid) ELSE SCHEMA_NAME(dbo.sysobjects.uid) END AS owner
        ///	, (CASE WHEN @cmplevel &lt; 90  THEN USER_NAME(dbo.sysobjects.uid) ELSE SCHEMA_NAME(dbo.sysobjects.uid) END) + &apos;.&apos; + (OBJECT_NAME(dbo.sysobjects.id)) AS tableName
        ///	, (CASE WHEN @cmplevel &lt; 90  THEN USER_NAME(dbo.sysob [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Script_GetForeignKeysForTable {
            get {
                return ResourceManager.GetString("Script_GetForeignKeysForTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare @cmplevel int
        ///select @cmplevel = cmptlevel 
        ///from  master..sysdatabases 
        ///where name = DB_NAME()
        ///
        ///SELECT 
        ///	O.id as objectID
        ///	, I.indid as indexID
        ///	, CAST(O.id AS VARCHAR) + &apos;,&apos; + CAST(I.indid AS VARCHAR) as completeindexID
        ///	, CASE WHEN @cmplevel &lt; 90 THEN USER_NAME(O.uid) ELSE SCHEMA_NAME(O.uid) END &apos;owner&apos;
        ///	, O.name as objectName
        ///	,  (CASE WHEN @cmplevel &lt; 90 THEN USER_NAME(O.uid) ELSE SCHEMA_NAME(O.uid) END)+ &apos;.&apos; + (I.name) as completename
        ///	, I.name as indexName
        ///	, CASE O.xtype WHEN &apos;V&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Script_GetIndexesForObjects {
            get {
                return ResourceManager.GetString("Script_GetIndexesForObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare @cmplevel int
        ///select @cmplevel = cmptlevel 
        ///from  master..sysdatabases 
        ///where name = DB_NAME()
        ///
        ///	
        ///SELECT 
        ///	object_id((CASE WHEN @cmplevel &lt; 90  THEN USER_NAME(dbo.sysobjects.uid) ELSE SCHEMA_NAME(dbo.sysobjects.uid) END) + &apos;.&apos; + (dbo.sysindexes.name)) as id 
        ///	, dbo.sysobjects.id as tableId
        ///	, CASE WHEN @cmplevel &lt; 90  THEN USER_NAME(dbo.sysobjects.uid) ELSE SCHEMA_NAME(dbo.sysobjects.uid) END AS tableOwner
        ///	, (CASE WHEN @cmplevel &lt; 90  THEN USER_NAME(dbo.sysobjects.uid) ELSE SCHEMA_NAME(db [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Script_GetPrimaryKeysForTable {
            get {
                return ResourceManager.GetString("Script_GetPrimaryKeysForTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare @cmplevel int
        ///select @cmplevel = cmptlevel 
        ///from  master..sysdatabases 
        ///where name = DB_NAME()
        ///
        ///SELECT 
        ///	id
        ///	, (((CASE WHEN @cmplevel &lt; 90 THEN USER_NAME(uid) ELSE SCHEMA_NAME(uid) END)) + &apos;.&apos; + (name) )as name
        ///	, CASE WHEN @cmplevel &lt; 90 
        ///		THEN USER_NAME(uid) 
        ///		ELSE SCHEMA_NAME(uid) 
        ///	END 
        ///	, name as ruleName
        ///	, crdate
        ///	, &apos;{0}&apos; as databasename 
        ///FROM sysobjects 
        ///WHERE 
        ///	type=&apos;R&apos; 
        ///	AND id NOT IN (SELECT constid FROM sysconstraints)
        ///ORDER BY
        ///	CASE WHEN @cmplevel &lt; 90 THEN USER_NA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Script_GetRules {
            get {
                return ResourceManager.GetString("Script_GetRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare @cmplevel int select @cmplevel = cmptlevel from  master..sysdatabases where name = DB_NAME()
        ///SELECT 
        ///	CASE WHEN @cmplevel &lt; 90  THEN USER_NAME(dbo.sysobjects.uid) ELSE SCHEMA_NAME(dbo.sysobjects.uid) END &apos;owner&apos;
        ///	, dbo.sysobjects.name
        ///	, (dbo.sysobjects.name) as &apos;qualifiedname&apos;
        ///	, (( CASE WHEN @cmplevel &lt; 90  THEN USER_NAME(dbo.sysobjects.uid) ELSE SCHEMA_NAME(dbo.sysobjects.uid) END)) + &apos;.&apos; + (dbo.sysobjects.name) as completename, dbo.sysindexes.[rows]
        ///	, FILEGROUP_NAME(dbo.sysindexes.groupid [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Script_GetTablesForCheckConstraint {
            get {
                return ResourceManager.GetString("Script_GetTablesForCheckConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare @cmplevel int
        ///select @cmplevel = cmptlevel 
        ///from  master..sysdatabases 
        ///where name = DB_NAME()
        ///
        ///SELECT 
        ///	usertype as id
        ///	, CASE WHEN @cmplevel &lt; 90 THEN USER_NAME(uid) ELSE SCHEMA_NAME(uid) END  as &apos;owner&apos;
        ///	, name
        ///	, (CASE WHEN @cmplevel &lt; 90 THEN USER_NAME(uid) ELSE SCHEMA_NAME(uid) END ) + &apos;.&apos; + (name) as completename
        ///	, type_name(xtype) as basetype
        ///	, OBJECT_NAME(domain) as boundrule
        ///	, OBJECT_NAME(tdefault) as bounddefault
        ///FROM systypes S WHERE xusertype&gt;256  
        ///ORDER BY 
        ///	CASE WHEN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Script_GetUserDataTypes {
            get {
                return ResourceManager.GetString("Script_GetUserDataTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare @cmplevel int select @cmplevel = cmptlevel from  master..sysdatabases where name = DB_NAME()
        ///select 
        ///	so.*,
        ///	(so.name) as &apos;qualifiedname&apos;,
        ///	CASE WHEN @cmplevel &lt; 90  THEN USER_NAME(so.uid) ELSE SCHEMA_NAME(so.uid) END  &apos;owner&apos; 
        ///from sysobjects so
        ///where ( so.xtype = &apos;U&apos;) AND so.id = {0}
        ///order by so.name.
        /// </summary>
        internal static string Script_GetUserTableById {
            get {
                return ResourceManager.GetString("Script_GetUserTableById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare @cmplevel int
        ///select @cmplevel = cmptlevel 
        ///from  master..sysdatabases 
        ///where name = DB_NAME()
        ///
        ///
        /// declare @tbl table
        ///(
        ///	objName sysname NULL,
        ///    objType char(2) NULL,
        ///    owner nvarchar(256) NULL,
        ///    candelete bit NULL,oldCandelete bit NULL,
        ///    caninsert bit NULL,oldCaninsert bit NULL,
        ///    canreferences bit NULL,oldCanreferences bit NULL,
        ///    canselect bit NULL,oldCanselect bit NULL,
        ///    canupdate bit NULL,oldCanupdate bit NULL,
        ///    canexecute bit NULL,oldCanexecute bit NULL
        ///)
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Script_ObjectsForPrivileges {
            get {
                return ResourceManager.GetString("Script_ObjectsForPrivileges", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap UserAdd {
            get {
                object obj = ResourceManager.GetObject("UserAdd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UserDelete {
            get {
                object obj = ResourceManager.GetObject("UserDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UserEdit {
            get {
                object obj = ResourceManager.GetObject("UserEdit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap users {
            get {
                object obj = ResourceManager.GetObject("users", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Warning {
            get {
                object obj = ResourceManager.GetObject("Warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Webcontrol_Webpartmgr {
            get {
                object obj = ResourceManager.GetObject("Webcontrol_Webpartmgr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
