//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PragmaSQL.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DBScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DBScripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PragmaSQL.Core.Resources.DBScripts", typeof(DBScripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @r table
        ///(
        ///  [Order] int null,
        ///  Type varchar(10) null,
        ///  Catalog sysname null,
        ///  [Schema] sysname null,
        ///  ParentName sysname null,
        ///  Name sysname null,
        ///  DisplayName sysname null,
        ///  DataType sysname null,
        ///  IsOffline bit
        ///)
        ///
        ///
        ///-- databases
        ///insert into @r([Order], Type,Name,DisplayName )
        ///select
        ///  0
        ///  ,&apos;Db&apos;  
        ///  , name 
        ///  , name
        ///from  master..sysdatabases 
        ///
        ///-- Users
        ///insert into @r( [Order],Type,Name,DisplayName )
        ///select 
        ///  1
        ///  ,&apos;Usr&apos; 
        ///  ,name
        ///  ,name
        ///from sysusers
        ///
        ///-- Tab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Script_CodeCompletionProposal {
            get {
                return ResourceManager.GetString("Script_CodeCompletionProposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @r table
        ///(
        ///  [Order] int null,
        ///  Type varchar(10) null,
        ///  Catalog sysname null,
        ///  [Schema] sysname null,
        ///  ParentName sysname null,
        ///  Name sysname null,
        ///  DisplayName sysname null,
        ///  DataType sysname null,
        ///  QualifiedDataType sysname null,
        ///  IsOffline bit
        ///)
        ///
        ///
        ///
        ///
        ///-- Tables
        ///insert into @r([Order], Type,Catalog,[Schema],ParentName, Name, DisplayName, DataType, QualifiedDataType )
        ///select
        ///  0
        ///  ,&apos;Tbl&apos;,TABLE_CATALOG, TABLE_SCHEMA,&apos;&apos;, TABLE_NAME , TABLE_NAME, &apos;Table&apos;,&apos;Table&apos;
        ///from  INFO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Script_CodeCompletionProposalWithoutProcParams {
            get {
                return ResourceManager.GetString("Script_CodeCompletionProposalWithoutProcParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXEC sp_fkeys @pktable_name = N.
        /// </summary>
        internal static string Script_ForeignKeyIn {
            get {
                return ResourceManager.GetString("Script_ForeignKeyIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXEC sp_fkeys @fktable_name = N.
        /// </summary>
        internal static string Script_ForeignKeys {
            get {
                return ResourceManager.GetString("Script_ForeignKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare @compLevel smallint
        ///select @compLevel = {0}
        ///
        ///select
        ///  so.*,
        ///  CASE WHEN @compLevel &lt; 90 
        ///	THEN  USER_NAME(so.uid) 
        ///	ELSE SCHEMA_NAME(so.uid)
        ///  END &apos;owner&apos;,
        ///  
        ///  CASE WHEN @compLevel &lt; 90 
        ///	THEN  (USER_NAME(so.uid)) + &apos;.&apos; + (so.name)  
        ///	ELSE (SCHEMA_NAME(so.uid)) + &apos;.&apos; + (so.name)  
        ///  END &apos;FullName&apos;
        ///from sysobjects so
        ///where 
        ///   so.xtype = &apos;TR&apos;
        ///order by
        /// CASE WHEN @compLevel &lt; 90 
        ///	THEN  USER_NAME(so.uid) 
        ///	ELSE SCHEMA_NAME(so.uid)
        ///  END,
        ///  so.name.
        /// </summary>
        internal static string Script_GetAllTriggers {
            get {
                return ResourceManager.GetString("Script_GetAllTriggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;WITH cols AS
        ///(
        ///    SELECT
        ///        c.column_id                               AS colorder,
        ///        c.name                                    AS name,
        ///        CASE WHEN ty.is_user_defined = 1
        ///             THEN QUOTENAME(SCHEMA_NAME(ty.schema_id)) + N&apos;.&apos; + QUOTENAME(ty.name)
        ///             ELSE ty.name
        ///        END                                       AS typename,
        ///        CASE
        ///            WHEN ty.name IN (N&apos;nchar&apos;, N&apos;nvarchar&apos;)
        ///                 THEN CASE WHEN c.max_length = -1 THEN -1 ELSE c.max_lengt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Script_GetColsAndParams {
            get {
                return ResourceManager.GetString("Script_GetColsAndParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @r table
        ///(
        ///  [dbid] smallint not null,
        ///  [Order] int null,
        ///  Type varchar(10) null,
        ///  Catalog sysname null,
        ///  [Schema] sysname null,
        ///  ParentName sysname null,
        ///  Name sysname null,
        ///  DataType sysname null,
        ///  CompatibilityLevel tinyint null
        ///)
        ///
        ///
        ///-- databases
        ///insert into @r([dbid],[Order], Type,Name,CompatibilityLevel )
        ///select
        ///  [dbid]
        ///  ,0
        ///  ,&apos;Db&apos;  
        ///  , name
        ///  , cmptlevel 
        ///from  master..sysdatabases 
        ///
        ///select * from @r.
        /// </summary>
        internal static string Script_GetDatabases {
            get {
                return ResourceManager.GetString("Script_GetDatabases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare @cmplevel int
        ///select @cmplevel = cmptlevel 
        ///from  master..sysdatabases 
        ///where name = DB_NAME()
        ///
        ///SELECT 
        ///	CASE WHEN @cmplevel &lt; 90 
        ///		THEN USER_NAME(types1.uid) 
        ///		ELSE SCHEMA_NAME(types1.uid) 
        ///	END &apos;owner&apos;,
        ///	CASE WHEN USER_NAME(types1.uid) = &apos;sys&apos; 
        ///		THEN LOWER(types1.name)  
        ///		ELSE LOWER( ((CASE WHEN @cmplevel &lt; 90  THEN USER_NAME(types1.uid) ELSE  SCHEMA_NAME(types1.uid) END )) + &apos;.&apos; + (types1.name)) 
        ///	END AS &apos;name&apos;,
        ///	CASE WHEN (CASE WHEN @cmplevel &lt; 90  THEN USER_NAME(types1.uid) EL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Script_GetDataTypes {
            get {
                return ResourceManager.GetString("Script_GetDataTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare @cmplevel int
        ///select @cmplevel = cmptlevel 
        ///from  master..sysdatabases 
        ///where name = DB_NAME()
        ///
        ///
        ///  SELECT 
        ///	I.name,
        ///	(
        ///	CASE WHEN @cmplevel &lt; 90 
        ///		THEN USER_NAME(O.uid) 
        ///		ELSE SCHEMA_NAME(O.uid) 
        ///	END ) &apos;owner&apos;
        ///	, O.id
        ///	, (O.name) as objectName 
        ///	, ( CASE WHEN @cmplevel &lt; 90 THEN USER_NAME(O.uid) ELSE SCHEMA_NAME(O.uid) END ) + &apos;.&apos; + (O.name) as QuotedFullName
        ///  FROM sysobjects O,sysindexes I 
        ///   WHERE I.indid = {0} AND O.id = {1} AND 
        ///  I.status&amp;2048!=2048 AND I.status&amp;4096!=409 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Script_GetIndexProperties {
            get {
                return ResourceManager.GetString("Script_GetIndexProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare @compLevel smallint
        ///select @compLevel = {0}
        ///
        ///select
        ///  so.*,
        ///  CASE WHEN @compLevel &lt; 90 
        ///	THEN  USER_NAME(so.uid) 
        ///	ELSE SCHEMA_NAME(so.uid)
        ///  END &apos;owner&apos;,
        ///  
        ///  CASE WHEN @compLevel &lt; 90 
        ///	THEN  
        ///		CASE WHEN so.uid IS NULL 
        ///			THEN (so.name)  
        ///			ELSE (USER_NAME(so.uid)) + &apos;.&apos; + (so.name)
        ///	    END  
        ///	ELSE 
        ///		CASE WHEN so.uid IS NULL 
        ///			THEN (so.name)  
        ///			ELSE (SCHEMA_NAME(so.uid)) + &apos;.&apos; + (so.name)
        ///	    END  
        ///  END &apos;FullName&apos;
        ///from sysobjects so
        ///where 
        ///   ( so.xtype = &apos;IF&apos; ) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Script_GetInlinedTableFunctions {
            get {
                return ResourceManager.GetString("Script_GetInlinedTableFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if exists (select * from dbo.syscomments where id=@id) 
        ///  select 
        ///    c.text, 
        ///    c.encrypted, 
        ///    c.number, 
        ///    xtype=convert(nchar(2), o.xtype),     
        ///    datalength(c.text), 
        ///    convert(varbinary(8000), c.text), 0 
        ///from dbo.syscomments c, dbo.sysobjects o     
        ///where o.id = c.id and c.id = @id
        ///order by c.number, c.colid option(robust plan).
        /// </summary>
        internal static string Script_GetObjectCreateScript {
            get {
                return ResourceManager.GetString("Script_GetObjectCreateScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///declare @cmplevel int
        ///select @cmplevel = cmptlevel 
        ///from  master..sysdatabases 
        ///where name = DB_NAME()
        ///
        ///select TOP 1 
        /// o.name,
        /// o.xtype,
        /// o.id ,CASE WHEN @cmplevel  &lt; 90 THEN  USER_NAME(o.uid) ELSE SCHEMA_NAME(o.uid) END &apos;owner&apos;
        ///from  sysobjects o
        ///where o.name = &apos;{0}&apos;.
        /// </summary>
        internal static string Script_GetObjectInfoByName {
            get {
                return ResourceManager.GetString("Script_GetObjectInfoByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select 
        ///text 
        ///from sysobjects AS o 
        ///join syscomments c on c.id = o.id 
        ///where o.name = &apos;{0}&apos; 
        ///order by o.name.
        /// </summary>
        internal static string Script_GetObjectScriptByName {
            get {
                return ResourceManager.GetString("Script_GetObjectScriptByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare @compLevel smallint
        ///select @compLevel = {0}
        ///
        ///select
        ///  so.*,
        ///  CASE WHEN @compLevel &lt; 90 
        ///	THEN  USER_NAME(so.uid) 
        ///	ELSE SCHEMA_NAME(so.uid)
        ///  END &apos;owner&apos;,
        ///  
        ///  CASE WHEN @compLevel &lt; 90 
        ///	THEN  
        ///		CASE WHEN so.uid IS NULL 
        ///			THEN (so.name)  
        ///			ELSE (USER_NAME(so.uid)) + &apos;.&apos; + (so.name)
        ///	    END  
        ///	ELSE 
        ///		CASE WHEN so.uid IS NULL 
        ///			THEN (so.name)  
        ///			ELSE (SCHEMA_NAME(so.uid)) + &apos;.&apos; + (so.name)
        ///	    END  
        ///  END &apos;FullName&apos;
        ///from sysobjects so
        ///where 
        ///    (so.xtype = &apos;FN&apos;)  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Script_GetScalarValuedFunctions {
            get {
                return ResourceManager.GetString("Script_GetScalarValuedFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare @compLevel smallint
        ///select @compLevel = {0}
        ///
        ///select
        ///  so.*,
        ///  CASE WHEN @compLevel &lt; 90 
        ///	THEN  USER_NAME(so.uid) 
        ///	ELSE SCHEMA_NAME(so.uid)
        ///  END &apos;owner&apos;,
        ///  
        ///  CASE WHEN @compLevel &lt; 90 
        ///	THEN  
        ///		CASE WHEN so.uid IS NULL 
        ///			THEN (so.name)  
        ///			ELSE (USER_NAME(so.uid)) + &apos;.&apos; + (so.name)
        ///	    END  
        ///	ELSE 
        ///		CASE WHEN so.uid IS NULL 
        ///			THEN (so.name)  
        ///			ELSE (SCHEMA_NAME(so.uid)) + &apos;.&apos; + (so.name)
        ///	    END  
        ///  END &apos;FullName&apos;
        ///from sysobjects so
        ///where 
        ///    (so.xtype = &apos;P&apos; or [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Script_GetStoredProcedures {
            get {
                return ResourceManager.GetString("Script_GetStoredProcedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///s.name AS [Name],
        ///s.object_id AS [ID],
        ///s.create_date AS [CreateDate],
        ///s.modify_date AS [DateLastModified],
        ///SCHEMA_NAME(s.schema_id) AS [Schema],
        ///s.base_object_name AS [BaseObjectName]
        ///FROM
        ///sys.synonyms AS s
        ///WHERE
        ///(s.name=N&apos;{0}&apos;).
        /// </summary>
        internal static string Script_GetSynonymInformation {
            get {
                return ResourceManager.GetString("Script_GetSynonymInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select
        ///  so.*
        ///  , SCHEMA_NAME(so.uid) as &apos;owner&apos; 
        ///  , CASE WHEN so.uid IS NULL 
        ///		THEN (so.name)
        ///		ELSE (SCHEMA_NAME(so.uid)) + &apos;.&apos; + (so.name)
        ///	END  AS FullName
        ///from sysobjects so
        ///where 
        ///  ( so.xtype = &apos;SN&apos;)
        ///order by
        ///  so.name.
        /// </summary>
        internal static string Script_GetSynonyms {
            get {
                return ResourceManager.GetString("Script_GetSynonyms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select
        ///  so.*
        ///  , 
        ///  CASE WHEN t.TABLE_SCHEMA IS NULL 
        ///	THEN &apos;&apos;
        ///	ELSE (t.TABLE_SCHEMA) 
        ///  END AS &apos;owner&apos; 
        ///  ,CASE WHEN t.TABLE_SCHEMA IS NULL 
        ///	THEN (so.name)
        ///	ELSE (t.TABLE_SCHEMA) + &apos;.&apos; + (so.name)  
        ///   END AS FullName
        ///	
        ///from sysobjects so
        ///left outer join INFORMATION_SCHEMA.TABLES t on so.name = t.TABLE_NAME
        ///where 
        ///  ( so.xtype = &apos;S&apos;)
        ///order by
        /// (t.TABLE_SCHEMA),
        /// so.name.
        /// </summary>
        internal static string Script_GetSystemTables {
            get {
                return ResourceManager.GetString("Script_GetSystemTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select   
        ///  sc.*, case when LOWER( st.name) = &apos;nvarchar&apos; or  LOWER( st.name) = &apos;nchar&apos; THEN sc.length / 2 ELSE sc.length END &apos;lengthx&apos;  
        ///, st.name as typename
        ///, case when( sc.status &amp; 0x80 = 0x80 )
        ///    then 1
        ///    else 0
        ///  end as isIdentity ,USER_NAME(so.uid) as &apos;owner&apos; 
        ///from syscolumns sc
        ///join sysobjects so on sc.id = so.id
        ///left outer join systypes st on sc.xtype = st.xusertype
        ///where ISNULL(sc.name,&apos;&apos;) &lt;&gt; &apos;&apos; 
        ///and so.name = &apos;{0}&apos;
        ///order by 
        ///isIdentity DESC
        ///,  sc.colorder
        ///, sc.name.
        /// </summary>
        internal static string Script_GetTableColumns {
            get {
                return ResourceManager.GetString("Script_GetTableColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///  IDENT_SEED(&apos;{0}&apos;) AS idSeed
        ///, IDENT_INCR(&apos;{0}&apos;) AS idIncrement
        ///FROM INFORMATION_SCHEMA.TABLES
        ///WHERE 
        ///  TABLE_NAME = &apos;{0}&apos;
        ///AND ( IDENT_SEED(&apos;{0}&apos;) IS NOT NULL )
        ///AND ( IDENT_INCR(&apos;{0}&apos;) IS NOT NULL ).
        /// </summary>
        internal static string Script_GetTableIdentityIncrementAndSeed {
            get {
                return ResourceManager.GetString("Script_GetTableIdentityIncrementAndSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare @compLevel smallint
        ///select @compLevel = {0}
        ///
        ///select
        ///  so.*,
        ///  CASE WHEN @compLevel &lt; 90 
        ///	THEN  USER_NAME(so.uid) 
        ///	ELSE SCHEMA_NAME(so.uid)
        ///  END &apos;owner&apos;,
        ///  
        ///  CASE WHEN @compLevel &lt; 90 
        ///	THEN  
        ///		CASE WHEN so.uid IS NULL 
        ///			THEN (so.name)  
        ///			ELSE (USER_NAME(so.uid)) + &apos;.&apos; + (so.name)
        ///	    END  
        ///	ELSE 
        ///		CASE WHEN so.uid IS NULL 
        ///			THEN (so.name)  
        ///			ELSE (SCHEMA_NAME(so.uid)) + &apos;.&apos; + (so.name)
        ///	    END  
        ///  END &apos;FullName&apos;
        ///from sysobjects so
        ///where 
        ///   ( (so.xtype = &apos;TF&apos;) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Script_GetTableValuedFunctions {
            get {
                return ResourceManager.GetString("Script_GetTableValuedFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare @compLevel smallint
        ///select @compLevel = {0}
        ///
        ///select
        ///  so.*,
        ///  CASE WHEN @compLevel &lt; 90 
        ///	THEN  USER_NAME(so.uid) 
        ///	ELSE SCHEMA_NAME(so.uid)
        ///  END &apos;owner&apos;,
        ///  CASE WHEN @compLevel &lt; 90 
        ///	THEN  (USER_NAME(so.uid)) + &apos;.&apos; + (so.name)  
        ///	ELSE (SCHEMA_NAME(so.uid)) + &apos;.&apos; + (so.name)  
        ///  END &apos;FullName&apos;
        ///from sysobjects so
        ///where 
        ///   so.xtype = &apos;TR&apos; and so.parent_obj = @parentid
        ///order by
        ///  CASE WHEN @compLevel &lt; 90 
        ///	THEN  USER_NAME(so.uid) 
        ///	ELSE SCHEMA_NAME(so.uid)
        ///  END
        ///  ,so.name.
        /// </summary>
        internal static string Script_GetTriggers {
            get {
                return ResourceManager.GetString("Script_GetTriggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @r table
        ///(
        ///  [Order] int null,
        ///  Type varchar(10) null,
        ///  Catalog sysname null,
        ///  [Schema] sysname null,
        ///  ParentName sysname null,
        ///  Name sysname null,
        ///  DataType sysname null
        ///)
        ///DECLARE @cmplevel int SELECT @cmplevel = cmptlevel FROM master..sysdatabases where name = DB_NAME() 
        ///
        ///-- Users
        ///IF @cmplevel &lt; 90 BEGIN 
        ///	INSERT INTO @r( [Order],Type,Name )
        ///    SELECT 1, &apos;Usr&apos;, name FROM sysusers WHERE uid!=0 AND isaliased=0 ORDER BY uid
        ///END ELSE BEGIN
        ///	INSERT INTO @r( [Order],Type,Name )
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Script_GetUsers {
            get {
                return ResourceManager.GetString("Script_GetUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select
        ///  so.*
        ///  , 
        ///  CASE WHEN t.TABLE_SCHEMA IS NULL 
        ///	THEN &apos;&apos;
        ///	ELSE (t.TABLE_SCHEMA) 
        ///  END AS &apos;owner&apos; 
        ///  ,CASE WHEN t.TABLE_SCHEMA IS NULL 
        ///	THEN (so.name)
        ///	ELSE (t.TABLE_SCHEMA) + &apos;.&apos; + (so.name)  
        ///   END AS FullName
        ///	
        ///from sysobjects so
        ///left outer join INFORMATION_SCHEMA.TABLES t on so.name = t.TABLE_NAME
        ///where 
        ///  ( so.xtype = &apos;U&apos;)
        ///order by
        /// (t.TABLE_SCHEMA),
        /// so.name.
        /// </summary>
        internal static string Script_GetUserTables {
            get {
                return ResourceManager.GetString("Script_GetUserTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select
        ///  so.*
        ///  , 
        ///  CASE WHEN t.TABLE_SCHEMA IS NULL 
        ///	THEN &apos;&apos;
        ///	ELSE (t.TABLE_SCHEMA) 
        ///  END AS &apos;owner&apos; 
        ///  ,CASE WHEN t.TABLE_SCHEMA IS NULL 
        ///	THEN (so.name)
        ///	ELSE (t.TABLE_SCHEMA) + &apos;.&apos; + (so.name)  
        ///   END AS FullName
        ///	
        ///from sysobjects so
        ///left outer join INFORMATION_SCHEMA.VIEWS t on so.name = t.TABLE_NAME
        ///where 
        ///  ( so.xtype = &apos;V&apos;)
        ///order by
        /// (t.TABLE_SCHEMA),
        /// so.name.
        /// </summary>
        internal static string Script_GetViews {
            get {
                return ResourceManager.GetString("Script_GetViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF NOT EXISTS (SELECT * FROM sysobjects WHERE id = OBJECT_ID(N&apos;[dbo].[PragmaSQLObjectGroup]&apos;) AND type in (N&apos;U&apos;))
        ///BEGIN
        ///CREATE TABLE [dbo].[PragmaSQLObjectGroup](
        ///	[ObjectID] [int] IDENTITY(1,1) NOT NULL,
        ///	[ParentID] [int] NULL,
        ///	[Name] [varchar](4000) NULL,
        ///	[ParentObjName] [varchar](4000) NULL,
        ///	[Description] [text] NULL,
        ///	[DescriptionFormat] [varchar](5) NULL,
        ///	[ObjType] [int] NULL,
        ///	[CreatedBy] [varchar](50) NULL,
        ///	[CreatedOn] [datetime] NULL,
        ///	[UpdatedBy] [varchar](50) NULL,
        /// CONSTRAINT [P [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Script_ObjectGroupingSupport {
            get {
                return ResourceManager.GetString("Script_ObjectGroupingSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @ParentID int
        ///DECLARE @tmp varchar(8000)
        ///DECLARE @comma varchar(1)
        ///
        ///SELECT @ParentID = ParentID FROM PragmaSQLObjectGroup
        ///WHERE ObjectID = {0}
        ///
        ///IF @ParentID IS NULL BEGIN
        ///  SELECT STR(@ParentID)
        ///  RETURN
        ///END
        ///
        ///SELECT @tmp = LTRIM(STR(@ParentID))
        ///SET @comma = &apos;,&apos;
        ///
        ///WHILE not ( @ParentID is null ) BEGIN
        ///  SELECT @ParentID = ParentID FROM PragmaSQLObjectGroup
        ///  WHERE ObjectID = @ParentID
        ///  IF @ParentID is null
        ///    break
        ///    
        ///  SELECT @tmp = @tmp + ISNULL(@comma,&apos;&apos;) + LTRIM(STR(@Paren [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Script_ObjectGroupingSupport_GetAllParents {
            get {
                return ResourceManager.GetString("Script_ObjectGroupingSupport_GetAllParents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF 
        ///( 
        ///  NOT EXISTS ( SELECT * FROM sysobjects WHERE id = OBJECT_ID(N&apos;[dbo].[PragmaSQLObjectGroup]&apos;) AND type in (N&apos;U&apos;))
        ///)
        ///OR
        ///( 
        /// NOT EXISTS (SELECT * FROM sysobjects WHERE id = OBJECT_ID(N&apos;[dbo].[spPragmaSQL_ObjectGroup_Delete]&apos;) AND type in (N&apos;P&apos;, N&apos;PC&apos;))
        ///)
        ///OR
        ///(
        ///  NOT EXISTS (SELECT * FROM sysobjects WHERE id = OBJECT_ID(N&apos;[dbo].[spPragmaSQL_ObjectGroup_Update]&apos;) AND type in (N&apos;P&apos;, N&apos;PC&apos;))
        ///)
        ///OR
        ///(
        ///  NOT EXISTS (SELECT * FROM sysobjects WHERE id = OBJECT_ID(N&apos;[dbo].[spPragmaSQL_ObjectGroup_Lis [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Script_ObjectGroupingSupportCheck {
            get {
                return ResourceManager.GetString("Script_ObjectGroupingSupportCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @Name varchar(8000)
        ///DECLARE @ParentName varchar(4000)
        ///DECLARE @ParentID int
        ///DECLARE @ObjectID int
        ///DECLARE @comma varchar(1)
        ///DECLARE @tmp varchar(8000)
        ///DECLARE @paths table(id int,name varchar(4000), path varchar(8000))
        ///DECLARE @objIds table(ObjectID int)
        ///
        ///SELECT @Name = &apos;{0}&apos;
        ///
        ///INSERT INTO @objIds 
        ///SELECT ObjectId FROM PragmaSQLObjectGroup
        ///WHERE LOWER(Name) = LOWER(@Name)
        ///
        ///
        ///DECLARE oCur CURSOR READ_ONLY FAST_FORWARD FOR
        ///SELECT ObjectID FROM @objIds
        ///
        ///  
        ///OPEN oCur
        ///WHILE (1=1) BEGIN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Script_ObjectGroupingSupportGroupStats {
            get {
                return ResourceManager.GetString("Script_ObjectGroupingSupportGroupStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare @cmplevel int select @cmplevel = cmptlevel  from  master..sysdatabases where name = DB_NAME()
        ///
        ///declare @types table(shortType varchar(3), longType varchar(50))
        ///insert into @types
        ///select &apos;U&apos;,&apos;Table&apos;
        ///
        ///insert into @types
        ///select &apos;V&apos;,&apos;View&apos;
        ///
        ///insert into @types
        ///select &apos;FN&apos;,&apos;UserDefinedFunction&apos;
        ///
        ///insert into @types
        ///select &apos;TF&apos;,&apos;UserDefinedFunction&apos;
        ///
        ///insert into @types
        ///select &apos;IF&apos;,&apos;UserDefinedFunction&apos;
        ///
        ///
        ///insert into @types
        ///select &apos;P&apos;,&apos;StoredProcedure&apos;
        ///
        ///insert into @types
        ///select &apos;X&apos;,&apos;S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Script_ObjectList {
            get {
                return ResourceManager.GetString("Script_ObjectList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;U&apos;, &apos;V&apos;, &apos;FN&apos;, &apos;TF&apos;, &apos;IF&apos;, &apos;P&apos;, &apos;X&apos;.
        /// </summary>
        internal static string Script_ObjectList_InCriteria {
            get {
                return ResourceManager.GetString("Script_ObjectList_InCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare @cmplevel int select @cmplevel = cmptlevel  from  master..sysdatabases where name = DB_NAME()
        ///
        ///declare @types table(shortType varchar(3), longType varchar(50))
        ///insert into @types
        ///select &apos;U&apos;,&apos;Table&apos;
        ///
        ///insert into @types
        ///select &apos;V&apos;,&apos;View&apos;
        ///
        ///insert into @types
        ///select &apos;FN&apos;,&apos;UserDefinedFunction&apos;
        ///
        ///insert into @types
        ///select &apos;TF&apos;,&apos;UserDefinedFunction&apos;
        ///
        ///insert into @types
        ///select &apos;IF&apos;,&apos;UserDefinedFunction&apos;
        ///
        ///
        ///insert into @types
        ///select &apos;P&apos;,&apos;StoredProcedure&apos;
        ///
        ///insert into @types
        ///select &apos;X&apos;,&apos;S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Script_ObjectListAll {
            get {
                return ResourceManager.GetString("Script_ObjectListAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select 
        ///  [Object] = o.name , 
        ///  user_name(p.uid) as &apos;UserOrRole&apos;, 
        ///  CASE action
        ///    WHEN 193 THEN &apos;SELECT&apos;
        ///    WHEN 195 THEN &apos;INSERT&apos;
        ///    WHEN 196 THEN &apos;DELETE&apos;
        ///    WHEN 197 THEN &apos;UPDATE&apos;
        ///    WHEN 224 THEN &apos;EXECUTE&apos;
        ///    WHEN 26 THEN &apos;REFERENCES&apos;
        ///    ELSE &apos;?&apos;
        ///  END as &apos;Action&apos;,
        ///  CASE protecttype
        ///    WHEN 204 THEN &apos;GRANT_W_GRANT&apos;
        ///    WHEN 205 THEN &apos;GRANT&apos;
        ///    WHEN 206 THEN &apos;DENY&apos;
        ///    ELSE &apos;?&apos;
        ///  END as &apos;ProtectType&apos; 
        ///from dbo.sysprotects p, dbo.sysobjects o
        ///where 
        ///  o.id = p.id 
        ///  and p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Script_Permissions {
            get {
                return ResourceManager.GetString("Script_Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET NOEXEC OFF
        ///SELECT distinct o.name, o.xtype, o.id
        ///from syscomments c
        ///join sysobjects o on o.id = c.id
        ///where o.name != &apos;{0}&apos;
        ///and (c.text like&apos;%{0}%&apos; or c.text like&apos;%{0}(%&apos;).
        /// </summary>
        internal static string Script_ReferencesAny {
            get {
                return ResourceManager.GetString("Script_ReferencesAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET NOEXEC OFF
        ///SELECT distinct o.name, o.xtype, o.id
        ///from syscomments c
        ///join sysobjects o on o.id = c.id
        ///where o.name != &apos;{0}&apos;
        ///and (c.text like &apos;% {0} %&apos; or c.text like &apos;% {0}(%&apos; or c.text like &apos;% {0} (%&apos;
        ///or c.text like &apos;%.{0} %&apos; or c.text like &apos;%.{0}(%&apos;).
        /// </summary>
        internal static string Script_ReferencesObject {
            get {
                return ResourceManager.GetString("Script_ReferencesObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select 
        ///  * 
        ///from INFORMATION_SCHEMA.COLUMNS 
        ///where TABLE_NAME = &apos;{0}&apos; 
        ///order by ORDINAL_POSITION.
        /// </summary>
        internal static string Script_Schema_Columns {
            get {
                return ResourceManager.GetString("Script_Schema_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select 
        ///  * 
        ///from INFORMATION_SCHEMA.ROUTINE_COLUMNS
        ///where TABLE_NAME = &apos;{0}&apos;
        ///order by ORDINAL_POSITION.
        /// </summary>
        internal static string Script_Schema_RoutineColumns {
            get {
                return ResourceManager.GetString("Script_Schema_RoutineColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select 
        ///  *
        ///from INFORMATION_SCHEMA.PARAMETERS 
        ///where SPECIFIC_NAME = &apos;{0}&apos; 
        ///order by ORDINAL_POSITION.
        /// </summary>
        internal static string Script_Schema_RoutineParams {
            get {
                return ResourceManager.GetString("Script_Schema_RoutineParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare @cmpLevel int
        ///select @cmpLevel = cmptlevel 
        ///from  master..sysdatabases 
        ///where name = DB_NAME()
        ///
        ///
        ///DECLARE @id int, @text nvarchar(4000), @ptrval varbinary(16)
        ///DECLARE @newtext nvarchar(4000), @ObjectName varchar(255), @QuoteOwnerName varchar(1000), @OwnerName varchar(511), @ varchar(1000)
        ///
        ///CREATE TABLE #Objects (id int, ObjectOwner varchar(255), ObjectName varchar(255), xtype char(2), QuoteOwnerName varchar(1000), OwnerName varchar(511), ObjectText text, ColText text)
        ///INSERT INTO #Objects ( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Script_SearchDbExtended {
            get {
                return ResourceManager.GetString("Script_SearchDbExtended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exec sp_help &apos;{0}&apos;.
        /// </summary>
        internal static string spHelp {
            get {
                return ResourceManager.GetString("spHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exec sp_helpconstraint &apos;{0}&apos;.
        /// </summary>
        internal static string spHelp_constraints {
            get {
                return ResourceManager.GetString("spHelp_constraints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exec sp_depends &apos;{0}&apos;.
        /// </summary>
        internal static string spHelp_Depends {
            get {
                return ResourceManager.GetString("spHelp_Depends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exec sp_fkeys @fktable_name = N&apos;{0}&apos;,@fktable_owner = N&apos;{1}&apos;.
        /// </summary>
        internal static string spHelp_foreignkeys {
            get {
                return ResourceManager.GetString("spHelp_foreignkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exec sp_fkeys @pktable_name = N&apos;{0}&apos;,@pktable_owner = N&apos;{1}&apos;.
        /// </summary>
        internal static string spHelp_foreignkeysin {
            get {
                return ResourceManager.GetString("spHelp_foreignkeysin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exec sp_special_columns &apos;{0}&apos;,&apos;{1}&apos;.
        /// </summary>
        internal static string spHelp_IdentityColumns {
            get {
                return ResourceManager.GetString("spHelp_IdentityColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exec sp_statistics &apos;{0}&apos;,&apos;{1}&apos;.
        /// </summary>
        internal static string spHelp_Statistics {
            get {
                return ResourceManager.GetString("spHelp_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exec sp_table_privileges &apos;{0}&apos;.
        /// </summary>
        internal static string spHelp_table_permissions {
            get {
                return ResourceManager.GetString("spHelp_table_permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exec sp_spaceused &apos;{0}&apos;.
        /// </summary>
        internal static string spHelp_UsedSpace {
            get {
                return ResourceManager.GetString("spHelp_UsedSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exec spPragmaSQL_ObjectGroup_Delete @ObjectID.
        /// </summary>
        internal static string spPragmaSQL_ObjectGroup_Delete {
            get {
                return ResourceManager.GetString("spPragmaSQL_ObjectGroup_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exec spPragmaSQL_ObjectGroup_GetHelpText @ObjectID.
        /// </summary>
        internal static string spPragmaSQL_ObjectGroup_GetHelpText {
            get {
                return ResourceManager.GetString("spPragmaSQL_ObjectGroup_GetHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exec spPragmaSQL_ObjectGroup_Insert @ParentID ,@Name, @ParentObjName ,@Description ,@DescriptionFormat ,@ObjType ,@CreatedBy, @ObjectID out
        ///.
        /// </summary>
        internal static string spPragmaSQL_ObjectGroup_Insert {
            get {
                return ResourceManager.GetString("spPragmaSQL_ObjectGroup_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exec spPragmaSQL_ObjectGroup_List @ParentID.
        /// </summary>
        internal static string spPragmaSQL_ObjectGroup_List {
            get {
                return ResourceManager.GetString("spPragmaSQL_ObjectGroup_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exec spPragmaSQL_ObjectGroup_Update @ObjectID ,@ParentID , @Name, @UpdatedBy.
        /// </summary>
        internal static string spPragmaSQL_ObjectGroup_Update {
            get {
                return ResourceManager.GetString("spPragmaSQL_ObjectGroup_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exec spPragmaSQL_ObjectGroup_UpdateDescription @ObjectID, @Description, @DescriptionFormat, @UpdatedBy.
        /// </summary>
        internal static string spPragmaSQL_ObjectGroup_UpdateDescription {
            get {
                return ResourceManager.GetString("spPragmaSQL_ObjectGroup_UpdateDescription", resourceCulture);
            }
        }
    }
}
