//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PragmaSQL.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RegularExpressions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegularExpressions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PragmaSQL.Core.Resources.RegularExpressions", typeof(RegularExpressions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (\/\*(\s*|.*?)*\*\/)|(--.*).
        /// </summary>
        internal static string SqlAnalyze_Comments {
            get {
                return ResourceManager.GetString("SqlAnalyze_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (declare|returns)\s+(?&apos;TableName&apos;\100+\w+)\s*(table)\s*\(\s*(?&apos;Columns&apos;(?&apos;ColNames&apos;\[?\s*\w+\s*\]?)\s*((?&apos;DataTypes&apos;bigint|binary\s*\(\s*\d+\s*\)|bit|char\s*\(\s*\d+\s*\)|datetime|decimal\s*\(\s*\d+\s*\)|decimal\s*\(\s*\d+\s*,\s*\d+\s*\)|float|image|int|money|nchar\s*\(\s*\d+\s*\)|ntext|numeric\s*\(\s*\d+\s*\)|numeric\s*\(\s*\d+\s*,\s*\d+\s*\)|nvarchar\s*\(\s*\d+\s*\)|real|smalldatetime|smallint|smallmoney|sql_variant|text|timestamp|tinyint|uniqueidentifier|varbinary\(\s*\d+\s*\)|varchar\(\s*\d+\s*\)|xml))( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SqlAnalyze_LocalTableVariable {
            get {
                return ResourceManager.GetString("SqlAnalyze_LocalTableVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from\s+(?&apos;TableName&apos;\[?\s*(\100?|\#{0,2})(\w+|\.+|\@+|\(+|\)+|,+|&apos;+|\&quot;+)*\s*\]?)\s+(?&apos;Ignore&apos;as|order|group|where|left|right|inner|outer|join)?\s*(?&apos;TableAlias&apos;\[?\s*\w+\s*\]?).
        /// </summary>
        internal static string SqlAnalyze_TableAliasFrom {
            get {
                return ResourceManager.GetString("SqlAnalyze_TableAliasFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to join\s+(?&apos;TableName&apos;\[?\s*(\100?|\#{0,2})(\w+|\.+|\@+|\(+|\)+|,+|&apos;+|\&quot;+)*\s*\]?)\s+(?&apos;Ignore&apos;as|order|group|where)?\s*(?&apos;TableAlias&apos;\[?\s*\w+\s*\]?).
        /// </summary>
        internal static string SqlAnalyze_TableAliasJoin {
            get {
                return ResourceManager.GetString("SqlAnalyze_TableAliasJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create\s+table\s+(?&apos;TableName&apos;\[?\s*\#{1,2}\w+\s*\]?)\s*\(\s*(?&apos;Columns&apos;(?&apos;ColNames&apos;\[?\s*\w+\s*\]?)\s*((?&apos;DataTypes&apos;bigint|binary\s*\(\s*\d+\s*\)|bit|char\s*\(\s*\d+\s*\)|datetime|decimal\s*\(\s*\d+\s*\)|decimal\s*\(\s*\d+\s*,\s*\d+\s*\)|float|image|int|money|nchar\s*\(\s*\d+\s*\)|ntext|numeric\s*\(\s*\d+\s*\)|numeric\s*\(\s*\d+\s*,\s*\d+\s*\)|nvarchar\s*\(\s*\d+\s*\)|real|smalldatetime|smallint|smallmoney|sql_variant|text|timestamp|tinyint|uniqueidentifier|varbinary\(\s*\d+\s*\)|varchar\(\s*\d+\s*\)|xml)) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SqlAnalyze_TempTable {
            get {
                return ResourceManager.GetString("SqlAnalyze_TempTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \100+\w+.
        /// </summary>
        internal static string SqlAnalyze_VariableNameOnly {
            get {
                return ResourceManager.GetString("SqlAnalyze_VariableNameOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&apos;Name&apos;\100+\w+)\s+(?&apos;DataType&apos;bigint|binary\s*\(\s*\d+\s*\)|bit|char\s*\(\s*\d+\s*\)|datetime|decimal\s*\(\s*\d+\s*\)|decimal\s*\(\s*\d+\s*,\s*\d+\s*\)|float|image|int|money|nchar\s*\(\s*\d+\s*\)|ntext|numeric\s*\(\s*\d+\s*\)|numeric\s*\(\s*\d+\s*,\s*\d+\s*\)|nvarchar\s*\(\s*\d+\s*\)|real|smalldatetime|smallint|smallmoney|sql_variant|text|timestamp|tinyint|uniqueidentifier|varbinary\(\s*\d+\s*\)|varchar\(\s*\d+\s*\)|xml).
        /// </summary>
        internal static string SqlAnalyze_VariableWithDataType {
            get {
                return ResourceManager.GetString("SqlAnalyze_VariableWithDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (\100+|\#{0,2})\w+.
        /// </summary>
        internal static string SqlAnalyze_Words {
            get {
                return ResourceManager.GetString("SqlAnalyze_Words", resourceCulture);
            }
        }
    }
}
